#----- General  -----#
globalconf:
  allowedOrigin: http://localhost
  apiport: "8081" #LEAVE AS IS IF RUNNED IN DOCKER


#----- Mikrotik -----#
routeros:
  debug: false
  address: "10.1.1.1"
  port: "8728"
  username: "user"
  password: "pass"
  async: false
  tls: false
  certname: "mikrotik.crt" # if you use TLS

#----- VPN Generator -----#
vpncreator:
  nginxfolder: "/app/output/" #Output folder for .zip DO NOT CHANGE IF LAUNCHED IN DOCKER
  caname: "dummyCA" #Name of the CA CASE SENSITIVE
  validtime: "365" #Validity Time
  keysize: "2048"
  countrycode: "JP"
  profilemap:   #Here is mapped the OpenVPN profile name and it's initials or shortname for profile name creation in secrets and cert
   #profilename : shortname in caps
    pull-ovpn: "PULL"
    non-pull-ovpn: "NOPULL"


